client_config_backend: file
client_config:
    client_id: 911520126045-goes97hck4c537ijo5jnpf1dbn1p6hpj.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive